# helpers { #src.wadoh_raccoon.utils.helpers }

`wadoh_raccoon.utils.helpers`



## Functions

| Name | Description |
| --- | --- |
| [clean_name](#src.wadoh_raccoon.utils.helpers.clean_name) | Clean name field by stripping non-alpha characters and converting to uppercase. |
| [date_format](#src.wadoh_raccoon.utils.helpers.date_format) | Format Dates |
| [get_secrets](#src.wadoh_raccoon.utils.helpers.get_secrets) | Get secrets |
| [gt_style](#src.wadoh_raccoon.utils.helpers.gt_style) | Style for GT Tables |
| [save_raw_values](#src.wadoh_raccoon.utils.helpers.save_raw_values) | save raw values |

### clean_name { #src.wadoh_raccoon.utils.helpers.clean_name }

```python
wadoh_raccoon.utils.helpers.clean_name(col: str)
```

Clean name field by stripping non-alpha characters and converting to uppercase.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**col**]{.parameter-name} [:]{.parameter-annotation-sep} [str]{.parameter-annotation}</code>

:   Name of column to clean

#### Returns {.doc-section .doc-section-returns}

<code>[]{.parameter-name} [:]{.parameter-annotation-sep} [pl.Expr:]{.parameter-annotation}</code>

:   a column of uppercase, non-alpha character, non-whitespace strings

#### Examples {.doc-section .doc-section-examples}

```{python}
import polars as pl
from wadoh_raccoon.utils import helpers

df = pl.DataFrame({
    "name": [
        "A$AP rocky",
        "50 cent",
        "sTevIe WoNdEr"
    ]
})

output = df.with_columns(helpers.clean_name("name").alias("clean_name"))

helpers.gt_style(df_inp=output)

```

### date_format { #src.wadoh_raccoon.utils.helpers.date_format }

```python
wadoh_raccoon.utils.helpers.date_format(df: pl.DataFrame, col: str)
```

Format Dates

Convert string dates into a yyyy-mm-dd format. 
The function uses pl.coalesce to try to process different formats.
For example, it will first try to convert m/d/y, and then if that doesn't work it will try d/m/y.
It's not perfect, but if someone messes up the date it's their fault.

**Note: it won't attempt to convert excel dates. If someone sends us excel dates we will file a lawsuit.**

#### Usage {.doc-section .doc-section-usage}

To be applied to a string date column.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**df**]{.parameter-name} [:]{.parameter-annotation-sep} [pl.DataFrame]{.parameter-annotation}</code>

:   a polars dataframe (needed to check if col is pl.Date type or not)

<code>[**col**]{.parameter-name} [:]{.parameter-annotation-sep} [str]{.parameter-annotation}</code>

:   a string column that has a date

#### Returns {.doc-section .doc-section-returns}

<code>[]{.parameter-name} [:]{.parameter-annotation-sep} [pl.Expr: ]{.parameter-annotation}</code>

:   a date column

#### Examples {.doc-section .doc-section-examples}

```{python}
import polars as pl
from wadoh_raccoon.utils import helpers

df = pl.DataFrame({
    "dates": [
        "2024-10-30",     # ISO format
        "30/10/2024",     # European format
        "10/20/2024",     # US format
        "10-30-2024",     # US format
        "October 30, 2024",  # Full month name format,
        "45496",           # an excel date LOL
        "2022-12-27 08:26:49"
    ]
})

output = (
    df
    .with_columns(
        new_date=helpers.date_format(df=df,col='dates')
    )
)

helpers.gt_style(df_inp=output)

```

### get_secrets { #src.wadoh_raccoon.utils.helpers.get_secrets }

```python
wadoh_raccoon.utils.helpers.get_secrets(vault, keys)
```

Get secrets

Retrieve secrets from Azure KeyVault.
This function will utilize the keys that are passed to retrieve the 
corresponding secrets.

**Note: Authenication takes place via DefaultAzureCredential which attempts
multiple authentication methods. One method is checking against Azure CLI 
if logged in.

#### Usage {.doc-section .doc-section-usage}

Use this function to securely retrieve secret values from Azure KeyVault
using the specified key(s). The function accepts either a single key or
multiple keys as a list.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**vault**]{.parameter-name} [:]{.parameter-annotation-sep} []{.parameter-annotation}</code>

:   Key vault url.

<code>[**keys**]{.parameter-name} [:]{.parameter-annotation-sep} []{.parameter-annotation}</code>

:   A single secret key or list of secret keys.

#### Returns {.doc-section .doc-section-returns}

<code>[]{.parameter-name} [:]{.parameter-annotation-sep} [str or tuple of str]{.parameter-annotation}</code>

:   If a single key is provided, returns the secret value as a string. If a list of keys is provided, returns a tuple of secret values in the  same order.

#### Examples {.doc-section .doc-section-examples}

```python
from wadoh_raccoon.utils import helpers

# Get a single secret
db_password = helpers.get_secrets("keyvault_url", "db-password")

# Get multiple secrets at once
username, password, api_key = helpers.get_secrets(
    "keyvault_url",
    ["db-username", "db-password", "api-key"]
)
```

### gt_style { #src.wadoh_raccoon.utils.helpers.gt_style }

```python
wadoh_raccoon.utils.helpers.gt_style(
    df_inp: pl.DataFrame,
    title: str = '',
    subtitle: str = '',
    add_striping_inp,
    index_inp,
)
```

Style for GT Tables

#### Usage {.doc-section .doc-section-usage}

Apply this style to a Polars DataFrame

#### Parameters {.doc-section .doc-section-parameters}

<code>[**df_inp**]{.parameter-name} [:]{.parameter-annotation-sep} [pl.DataFrame]{.parameter-annotation}</code>

:   a polars dataframe

<code>[**title**]{.parameter-name} [:]{.parameter-annotation-sep} [str]{.parameter-annotation} [ = ]{.parameter-default-sep} [\'\']{.parameter-default}</code>

:   a title for the table (optional)

<code>[**subtitle**]{.parameter-name} [:]{.parameter-annotation-sep} [str]{.parameter-annotation} [ = ]{.parameter-default-sep} [\'\']{.parameter-default}</code>

:   a subtitle for the table (optional, must have a title if using a subtitle)

<code>[**add_striping_inp**]{.parameter-name} [:]{.parameter-annotation-sep} []{.parameter-annotation} [ = ]{.parameter-default-sep} [True]{.parameter-default}</code>

:   striping in the table True or False

<code>[**index_inp**]{.parameter-name} [:]{.parameter-annotation-sep} []{.parameter-annotation} [ = ]{.parameter-default-sep} [True]{.parameter-default}</code>

:   add a column for the row number and label it `index`

#### Returns {.doc-section .doc-section-returns}

<code>[]{.parameter-name} [:]{.parameter-annotation-sep} [GT]{.parameter-annotation}</code>

:   a GT object (great_tables table)

#### Examples {.doc-section .doc-section-examples}

```{python}
import polars as pl
from wadoh_raccoon.utils import helpers
df = pl.DataFrame({
    "x": [1,1,2],
    "y": [1,2,3]
})

```
A table with a title/subtitle:

```{python}
helpers.gt_style(df_inp=df,title="My Title",subtitle="My Subtitle")

```

No title/subtitle
```{python}
helpers.gt_style(df_inp=df)
```

Without an index:
```{python}
helpers.gt_style(df_inp=df,index_inp=False)
```

Without striping:
```{python}
helpers.gt_style(df_inp=df,add_striping_inp=False)
```

### save_raw_values { #src.wadoh_raccoon.utils.helpers.save_raw_values }

```python
wadoh_raccoon.utils.helpers.save_raw_values(
    df_inp: pl.DataFrame,
    primary_key_col: str,
)
```

save raw values

#### Usage {.doc-section .doc-section-usage}

Converts a polars dataframe into a dataframe with all columns in a struct column.
It's good for saving raw outputs of data.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**df_inp**]{.parameter-name} [:]{.parameter-annotation-sep} [pl.DataFrame]{.parameter-annotation}</code>

:   a polars dataframe

<code>[**primary_key_col**]{.parameter-name} [:]{.parameter-annotation-sep} [str]{.parameter-annotation}</code>

:   column name for the primary key (submission key, not person/case key)

#### Returns {.doc-section .doc-section-returns}

<code>[**df**]{.parameter-name} [:]{.parameter-annotation-sep} [pl.DataFrame]{.parameter-annotation}</code>

:   a dataframe

#### Examples {.doc-section .doc-section-examples}

```{python}
import polars as pl
from wadoh_raccoon.utils import helpers

data = pl.DataFrame({
    "lab_name": ["PHL", "MFT", "ELR","PHL"],
    "first_name": ["Alice", "Bob", "Charlie", "Charlie"],
    "last_name": ["Smith", "Johnson", "Williams", "Williams"],
    "WA_ID": [1,2,4,4]
})

received_submissions_df = (
        helpers.save_raw_values(df_inp=data,primary_key_col="WA_ID")
)

helpers.gt_style(data)

```

```{python}
helpers.gt_style(received_submissions_df)
```